6 functionality to get all products
smruti-banty/ApparelAvenue pull request #27
Opened 2024-09-19 05:03 UTC by Smita-Sonu

- [x] get all products

2024-09-19 05:03 UTC, Smita-Sonu commented
get all products

2024-09-21 03:09 UTC, Smita-Sonu commented
get all products

2024-09-22 05:31 UTC, smruti-banty requested changes

2024-09-22 05:31 UTC, smruti-banty commented on backend/src/main/java/com/ApparelAvenue/backend/controller/ProductController.java
> +    public ProductController(ProductService productService) {
Remove constructor, You are using annotation to create it

2024-09-22 05:31 UTC, smruti-banty commented on backend/src/main/java/com/ApparelAvenue/backend/service/ProductService.java
> +
Remove line break

2024-09-22 05:34 UTC, smruti-banty approved these changes
LGTM.

2024-09-22 05:35 UTC, merged