Add validation on product request dto and product update request dto
smruti-banty/ApparelAvenue pull request #91
Opened 2024-09-24 03:20 UTC by SmrutiSnigdhaSenapati

- [x] Add validation on product request dto and product update request dto

2024-09-24 03:51 UTC, smruti-banty commented on backend/src/main/java/com/ApparelAvenue/backend/controller/ProductController.java
> +        System.out.println("Received request: " + dto);
Remove system.out.println

2024-09-24 03:52 UTC, smruti-banty requested changes
Also add this login for Product update

2024-09-24 04:37 UTC, SmrutiSnigdhaSenapati commented
- [x] Add validation on product request dto and product update request dto

2024-09-25 02:14 UTC, smruti-banty approved these changes
LGTM.

2024-09-25 02:14 UTC, merged